name: sample-monorepo
services:
- environment_slug: go
  image:
    registry_type: DOCR
    repository: registry.digitalocean.com/<my-registry>/<my-image>
    tag: test2
  name: api
  routes:
  - path: /api
  source_dir: api
- environment_slug: go
  image:
    registry_type: DOCR
    repository: registry.digitalocean.com/<my-registry>/<my-image>
    tag: latest
  name: webhook
  routes:
  - path: /webhook
  source_dir: webhook
static_sites:
- environment_slug: html
  error_document: error.html
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-monorepo
  index_document: hello.html
  name: frontend
  routes:
  - path: /
  source_dir: frontend
- dockerfile_path: landing/Dockerfile
  error_document: error.html
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-monorepo
  name: landing
  output_dir: /app
  routes:
  - path: /landing
  source_dir: landing
workers:
- dockerfile_path: worker/Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: digitalocean/sample-monorepo
  name: worker
  run_command: sh -c "cat ./ok && sleep infinity"
  source_dir: worker
