name: DigitalOcean App Platform deployment
description: Deploy application to DigitalOcean's App Platform or Update DOCR image in the DigitalOcean's App Platform.
branding:
  icon: 'upload-cloud'
  color: 'blue'

inputs:
  app_name:
    description: Name of the app. (The name of the app must be unique across all apps in the same account.)
    required: true
  token:
    description: DigitalOcean Personal Access Token.(use https://docs.digitalocean.com/reference/api/create-personal-access-token/ for creating new token)
    required: true
  list_of_image:
    description: (OPTIONAL)a json array of objects with the properties name (description), repository (repo url), tag (image tag)
    required: false
    default: ""

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.list_of_image }}"
    - "${{ inputs.app_name }}"
    - "${{ inputs.token }}"